#!/usr/bin/env python3

import click

from cli import init, apply, destroy, fmt, import_cmd, rm, taint

VERSION = "0.1"


@click.group()
@click.version_option(version=VERSION, prog_name='terrarium')
def terrarium():  # pragma: no cover
    """terrarium cli"""
    pass


terrarium.add_command(init)
terrarium.add_command(apply)
terrarium.add_command(destroy)
terrarium.add_command(fmt)
terrarium.add_command(import_cmd)
terrarium.add_command(rm)
terrarium.add_command(taint)

if __name__ == '__main__':  # pragma: no cover
    terrarium()
